.\" -*- nroff -*-
.\" Copyright (C) 2004 Thorsten Kukuk
.\" Author: Thorsten Kukuk <kukuk@suse.de>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License version 2 as
.\" published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software Foundation,
.\" Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.TH grpconv 8 "January 2004" "pwdutils"
.SH NAME
grpconv \- convert to shadow group
.SH SYNOPSIS
.TP 5
\fBgrpconv\fR
.SH DESCRIPTION
Since \fI/etc/gshadow\fR is not supported by this system,
\fBgrpconv\fR does nothing except printing an error message.
.SH FILES
/etc/group \- group account information
.SH SEE ALSO
.BR group (5)
.SH AUTHOR
Thorsten Kukuk <kukuk@suse.de>
