.\" -*- nroff -*-
.\" Copyright (C) 2002, 2003, 2004 Thorsten Kukuk
.\" Author: Thorsten Kukuk <kukuk@suse.de>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License version 2 as
.\" published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software Foundation,
.\" Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.TH rpasswd 1 "January 2004" "pwdutils"
.SH NAME
rpasswd \- change user password on remote server
.SH SYNOPSIS
.TP 5
\fBrpasswd\fR [\fB-4\fR|\fB-6\fR] [\fB-a\fR] [\fB-f \fIconfig-file\fR] [\fB-h \fIhostname\fR] [\fB-v\fR] [\fB-p \fIport\fR] [\fB--reqcert \fIlevel\fR] [\fB--no-slp\fR] [\fBname\fR]
.SH DESCRIPTION
\fBrpasswd\fR changes passwords for user accounts on a remote server over
a secure SSL connection. A normal user may only change the password for
their own account, if the user knows the password of the administrator
account (in the moment this is the root password on the server), he
may change the password for any account if he calls \fBrpasswd\fR with
the \fB-a\fR option.
.SH OPTIONS
.TP
.B "\-a, \-\-admin"
With this option, \fBrpasswd\fR connects as administrator user to the
remote server. The user has to supply the administrator password
and can change then every password.
.TP
.BI "\-f, \-\-config-file" " config-file"
Specify another configuration file than \fI/etc/rpasswd.conf\fR.
.TP
.BI "\-h, \-\-hostname" " hostname"
Specify the name of the server, where
.BR rpasswdd (8)
is running.
.TP
.BI "\-p, \-\-port" " portnumber"
Specify the portnumber on which the server process
.BR rpasswdd (8)
is listening.
.TP
.BI "\-r, \-\-reqcert" " never|allow|try|hard"
.RS
Specifies what checks to perform on server certificates in
a SSL session. The default for this option is
.IR hard .
.TP
.B never
\fIrpasswd\fR will not request or check any server certificate.
.TP
.B allow
The server certificate is requested. If no certificate is provided,
the session proceeds normally. If a bad certificate is provided, a
warning will be shown but the session proceeds normally.
.TP
.B try
The server certificate is requested. If no certificate is provided,
the session proceeds normally. If a bad certificate is provided,
the session is immediately terminated.
.TP
.B hard
The server certificate is requested. If no or a bad certificate is
provided, the session is immediately terminated.
.RE
.TP
.B "-4"
\fBrpasswd\fR will only use IPv4 to connect to the server.
.TP
.B "-6"
\fBrpasswd\fR will only use IPv6 to connect to the server.
.TP
.B "\-\-no-slp"
If compiled with SLP support, \fBrpasswd\fR will not use SLP
to find a server.
.TP
.B "\-v, \-\-verbose"
Be verbose, print SSL connection data.
.SH FILES
/etc/rpasswd.conf \- configuration file
.SH SEE ALSO
.BR passwd (1),
.BR passwd (5),
.BR rpasswd.conf (5),
.BR rpasswdd (8)
.SH AUTHOR
Thorsten Kukuk <kukuk@suse.de>
