#!/bin/bash

export LANG=C

TEMPDIR=`mktemp -d tests.XXXXXX`

touch $TEMPDIR/passwd
touch $TEMPDIR/group

./groupadd -P $TEMPDIR -r -o -g 99 test_userdel1
./useradd -P $TEMPDIR -g 99 -G "" test_userdel1
RET=$?
if [ $RET != 0 ]; then
        rm -rf $TEMPDIR
        exit $RET
fi
rm -rf $TEMPDIR/group
touch $TEMPDIR/group
./userdel -P $TEMPDIR test_userdel1 &> /dev/null
RET=$?
if [ $RET != 0 ]; then
        rm -rf $TEMPDIR
        exit $RET
fi

if [ -s $TEMPDIR/passwd ]; then
	cp $TEMPDIR/passwd tst-userdel.passwd
	rm -rf $TEMPDIR
	exit $RET
fi

rm -rf $TEMPDIR
exit 0

